[phases.setup]
nixPkgs = ["nodejs", "postgresql", "redis"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npm run build", "npx prisma generate"]

[start]
cmd = "npm start"
